app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(app = "click")
app$setInputs(shrub = FALSE)
app$setInputs(tree = FALSE)
app$setInputs(other = FALSE)
app$setInputs(H = FALSE)
app$setInputs(SM = FALSE)
app$setInputs(SSD = FALSE)
app$setInputs(theme = "Growth forms")
app$setInputs(find = "arab")
app$setInputs(species = "Arabidopsis thaliana")
app$setInputs(sep = ";")
app$uploadFile(file1 = "example.csv")
app$setInputs(colors = "Stage")
app$snapshot()
